CREATE TABLE refresh_tokens (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code UUID UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);