CREATE TABLE email_verification_codes (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code VARCHAR(60) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);
